db:
  adapter: postgresql
  encoding: unicode
  pool: 10
  host: localhost
  username: pocketmoon
  password: ""
  database: hn_hiring


# x | y | z - if any of these words encountered
# case-insensitive
keywords:
  - REMOTE
  - ONSITE
  - react | react.js | reactjs
  - angular | AngularJS | Angular2
  - Ember | Ember.js | Emberjs
  - node | nodejs | node.js | javascript | react | reactjs| angular | AngularJS | ES6
  - ruby | rails | sinatra
  - elixir
  - phoenix
  - Julia
  - elixir | phoenix
  - Android
  - ios | iphone
  - java | JVM
  - C# | ASP.NET | .NET | mono
  - Scala
  - Python | Celery | Django
  - Go | golang
  - golang
  - r
  - postgres | PostgreSQL
  - mysql
  - cassandra
  - Erlang
  - React Native
  - MongoDB | Mongo
  - RabbitMQ
  - Hadoop
  - Spark
  - ElasticSearch
  - Redis
  - Objective-C
  - C
  - C++ C++11
  - Haskell
  - Docker
  - PHP
  - nosql





# https://news.ycombinator.com/item?id=ID
# Ask HN: Who is hiring? (July 2015) thread
pages:
  - 12016568 # July 2016
  - 11814828 # June 2016
  - 11611867 # May 2016
  - 11405239 # April 2016
  - 11202954 # (March 2016)
  - 11012044 # February 2016
  - 10822019 # (January 2016)
  - 10655740 # December 2015)
  - 10492086 # (November 2015)
  - 10311580 # (October 2015
  - 10152809 # (September 2015)
  - 9996333 #  (August 2015)
  - 9812245 # July 2015
  - 9639001 # (June 2015)
  - 9471287 # (May 2015)
  - 9303396 # (April 2015)
  - 9127232 # (March 2015)
  - 8980047 # (February 2015)
  - 8822808 # (January 2015)
  - 8681040 # (December 2014)
  - 8542892 # (November 2014)
  - 8394339 # (October 2014)
  - 8252715 # (September 2014)
  - 8120070 # (August 2014)
  - 7970366 # (July 2014)
  - 7829042 # (June 2014)
  - 7679431 # (May 2014)
  - 7507765 # (April 2014)
  - 7324236 # (March 2014)
  - 7162197 # (February 2014)
  - 6995020 # (January 2014)
  - 6827554 # (December 2013)
  - 6653437 # (November 2013)
  - 6475879 # (October 2013)
  - 6310234 # (September 2013)
  - 6139927 # (August 2013)
  - 5970187 # (July 2013)
  - 5803764 # (June 2013)
  - 5637663 # (May 2013)
  - 5472746 # (April 2013)
  - 5304169 # (March 2013)
  - 5150834 # (February 2013)
  - 4992617 # (January 2013)
  - 4857714 # (December 2012)
  - 4727241 # (November 2012)
  - 4596375 # (October 2012)
  - 4463689 # (September 2012)
  - 4323597 # (August 2012)
  - 4184755 # (July 2012)
  - 4053076 # (June 2012)
  - 3913997 # (May 2012)
  - 3783657 # (April 2012)
  - 3652041 # (March 2012)
  - 3537881 # (February 2012)
  - 3412900 #(January 2012)
